### ISSUE TITLE
Sprockets undefined

### ISSUE THREAD

**Issue by sasha-bichkov** [ai/evil-blocks#38]
Hi, @ai !
I have a problem with evil-blocks when I'm trying to use it in my app.

> evil-blocks-rails.rb:17:in `install': undefined method `append_path' for nil:NilClass (NoMethodError)

I've created a new rails app, but I've got the same error.

Steps:
  1.  Rails new app
  2.  Add gem 'evil-blocks-rails' to Gemfile
  3.  Bundle install
  4.  Rails s

If I removed the gem I haven't the error.

ruby: 2.2.2
rails: 4.2.5

**Comment by sasha-bichkov** [comment]
I've changed sprockets-rails to 2.3.3 and my app works!

But it doesn't work with sprockets-rails 3.0.0 ( it was released 11 days ago ).

**Comment by ai** [comment]
Sorry, Evil Block is not really supported right now. PR is welcome.
